apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-app
spec:
  selector:
    matchLabels:
      app: hello-world-app
  replicas: 3
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: hello-world-app
        image: docker.io/charucheema1/helloapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
